### ISSUE TITLE
some questions about scripts

### ISSUE THREAD

**Issue by zer0-1s** [Who1sCarl/pwnenv#1]
➜  ~ python3 exp.py
[+] Starting local process './simplerop' argv=[b'./simplerop'] : pid 4655
[DEBUG] Received 0x23 bytes:
    b"ROP is easy is'nt it ?\n"
    b'Your input :'
[*] running in new terminal: /usr/bin/gdb -q  "./simplerop" 4655
[DEBUG] Launching a new terminal: ['/usr/bin/x-terminal-emulator', '-e', '/usr/bin/gdb -q  "./simplerop" 4655']
[-] Waiting for debugger: debugger exited! (maybe check /proc/sys/kernel/yama/ptrace_scope)

我运行时发现gdb好像没办法attach，报错说gdb版本过高，echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope更改仍无效，不知道是不是大佬脚本的问题

**Comment by Who1sCarl** [comment]
echo 0 | sudo tee  /proc/sys/kernel/yama/ptrace_scope
echo 0 | sudo tee  /proc/sys/kernel/randomize_va_space
这样应该就没问题了，脚本没问题，把随机化关掉即可。
